# Generated by Django 5.0.4 on 2024-05-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('location', models.CharField(default='', max_length=15)),
                ('parents_names', models.CharField(max_length=15)),
                ('fee', models.IntegerField()),
                ('period_of_stay', models.CharField(max_length=20)),
                ('baby_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('total_cost', models.IntegerField(blank=True, default=0)),
                ('payee', models.CharField(default=0, max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('location', models.CharField(default='Kabalagala', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('next_of_kin', models.CharField(max_length=20)),
                ('nin', models.CharField(max_length=20)),
                ('recommender_name', models.CharField(max_length=20)),
                ('religion', models.CharField(blank=True, max_length=25)),
                ('education_level', models.CharField(max_length=255)),
                ('sitter_number', models.CharField(max_length=8)),
                ('contacts', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('brought_by', models.CharField(max_length=15)),
                ('baby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('parents_names', models.CharField(max_length=15)),
                ('baby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare.baby')),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='sitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare.sitter'),
        ),
    ]
