# Generated by Django 5.0.6 on 2024-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='timed_at',
        ),
        migrations.AlterField(
            model_name='departure',
            name='departure_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
