# Generated by Django 5.0.6 on 2024-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_alter_baby_age_alter_baby_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babypayment',
            name='monthly_f',
        ),
        migrations.RemoveField(
            model_name='babypayment',
            name='monthly_h',
        ),
        migrations.AlterField(
            model_name='baby',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
