# Generated by Django 5.0.6 on 2024-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0003_remove_babypayment_monthly_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterpayment',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount_UGX',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_issued_out',
            field=models.IntegerField(default=0),
        ),
    ]
