# Generated by Django 5.0.6 on 2024-05-18 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0004_sitterpayment_total_amount_alter_stock_amount_ugx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='baby',
            name='parents_names',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='baby',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='balance_left',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='paid_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
