# Generated by Django 5.0.6 on 2024-05-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0005_alter_baby_age_alter_baby_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity_in_stock',
        ),
    ]
