# Generated by Django 5.0.6 on 2024-05-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0006_remove_stock_quantity_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='amount_UGX',
        ),
        migrations.AddField(
            model_name='issuing',
            name='stock',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='daycare.stock'),
        ),
    ]
